development:
  adapter: postgresql
  encoding: unicode
  database: profile_rails
  pool: 5
  username: postgres
  password: postgres
test:
  adapter: postgresql
  encoding: unicode
  database: profile_rails
  pool: 5
  username: postgres
  password: postgres

production:
  adapter: postgresql
  encoding: unicode
  database: profile_rails
  pool: 5
  username: postgres
  password: postgres